### ISSUE TITLE
Feature request: preserve text in the SVG output

### ISSUE THREAD

**Issue by stereobooster** [vizdom-dev/vizdom#12]
I guess, you already has this in your backlog. I decided also post it here for transparency.

As of now text converted to paths, which makes it unsearchable (<kbd>Cmd</kbd> + <kbd>F</kbd> doesn't work)

**Comment by stereobooster** [comment]
FYI: https://d2lang.com/ embeds font in SVG

```css
.d2-2891781443 .text-mono {
	font-family: "d2-2891781443-font-mono";
}
@font-face {
	font-family: d2-2891781443-font-mono;
	src: url("data:application/font-woff;base64,...");
}
```

Not sure this is an ideal solution., but another idea for you
